---
markdown: kramdown

permalink: /:title

plugins:
  - jekyll-paginate

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock

paginate: 10

sass:
  style: :compressed


