---
source: .
destination: ./_site
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true

markdown: kramdown

permalink: /:title/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://blog.hplogsdon.com"
color-scheme: auto
title: HPLogsdon

defaults:
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

paginate: 10

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

sidebar:
  - link: /about
    name: About
  - link: https://github.com/hplogsdon
    icon: fa-regular fa-brands fa-github
    name: Github
  - link: https://bsky.app/profile/hplogsdon.com
    icon: fa-regular fa-brands fa-bluesky
    name: Bluesky
  - link: /atom.xml
    icon: fa-regular fa-rss
    name: RSS
